name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: release linux-amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.4"
      - name: Install dependencies
        run: nimble install -y --depsOnly
      - name: Build release binary
        run: nim c -d:release --out:dp src/dp.nim
      - name: Package
        run: tar -czf dp-linux-amd64.tar.gz dp
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dp-linux-amd64.tar.gz
