name: tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.4"
      - name: Cache Nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            ~/.cache/nim
          key: ${{ runner.os }}-nim-${{ hashFiles('devpilot.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nim-
      - name: Install dependencies
        run: make tidy
      - name: Verify
        run: make verify
      - name: Build
        run: make build
