name: release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.artifact }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: "{{kebab_name}}-linux-amd64"
          - os: ubuntu-24.04-arm
            artifact: "{{kebab_name}}-linux-arm64"
          - os: macos-15-intel
            artifact: "{{kebab_name}}-macos-amd64"
          - os: macos-14
            artifact: "{{kebab_name}}-macos-arm64"
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Package
        run: tar -czf "${{ matrix.artifact }}.tar.gz" build
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}.tar.gz

